# Generated by Django 5.0.7 on 2024-08-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heimdall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holder',
            name='cpf',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='holder',
            name='phone',
            field=models.CharField(max_length=30),
        ),
    ]
